---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.enviroment }}-wordpress
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.enviroment }}-wordpress-local
  local:
    path: /mnt/k8s/{{ .Values.enviroment }}-wordpress
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vserver1207
